server:
  port: 8080
  ssl:
    key-store: 1969641_www.man-help.cn.pfx
    key-store-type: PKCS12
    key-store-password: EsjAGiQ4

spring:
  profiles : test
  jmx:
    enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    cache-period: 0
  template:
    cache: false
  resources:
    static-locations: classpath:/static/
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.142.246:345689/thssddfa
    username: sdsadfafajk
    password: &*AD*ADADJ
    initialSize: 50
    maxActive: 300
    minIdle: 50
    maxWait: 1000
    defaultAutoCommit: true
    timeBetweenEvictionRunsMillis: 600000
    numTestsPerEvictionRun: 3
    minEvictableIdleTimeMillis: 1800000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    validationQuery: select 1
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true

mybatis:
  mapperLocations: classpath:/mapper/*.xml,classpath:/mapper/*/*.xml


